batch-size: 8
check-mode: letter+word
debug: true
default-regexp:
    - (?i)['"]?(password|passwd|token|api_key|secret)['"]?[=:\s][\s]*?['"]?([^'"\s]+)['"]?
defaultexclude: ^(\.git|.*\.zip|.*\.gz|.*\.xz|.*\.bz2|.*\.zstd|.*\.7z|.*\.dll|.*\.iso|.*\.bin|.*\.tar|.*\.exe)$
exclude: ""
fptn: .*
group-index-a: []
group-index-b: []
path-exclude: ""
profile: ""
regexp: []
save-config: cred-detect-config.yaml
skipbinary: true
words-list-url: ""
